robstride_bridge_node:
  ros__parameters:
    joint_names:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
    motor_ids:
      - 1
      - 2
      - 3
      - 4
    kp_gains:
      - 30.0
      - 80.0
      - 30.0
      - 30.0
    kd_gains:
      - 0.5
      - 2.0
      - 0.5
      - 0.5
    host_id: 255