robstride_bridge_node:
  ros__parameters:
    joint_names:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
    motor_ids:
      - 1
      - 2
      - 3
      - 4
    kp_gains:
      - 30.0
      - 30.0
      - 30.0
      - 30.0
    kd_gains:
      - 0.5
      - 0.5
      - 0.5
      - 0.5
    host_id: 255
    gravity_comp_k2a: 0.0
    gravity_comp_k2b: 0.0
    gravity_comp_k3: 0.0
    torque_limit: 15.0
    velocity_limit: 30.0